
export const SET_NETWORKING_FETCHING = 'SET_NETWORKING_FETCHING';
export const SET_NETWORKING_SUCCESS = 'SET_NETWORKING_SUCCESS';
export const SET_NETWORKING_ERROR = 'SET_NETWORKING_ERROR';
export const SET_NETWORKING_IDLE = 'SET_NETWORKING_IDLE';
export const CLEAR_NETWORKING_NODES = 'CLEAR_NETWORKING_NODES';

export const ADD_LIST_ITEMS = 'ADD_LIST_ITEMS';
export const SET_LIST_ITEMS = 'SET_LIST_ITEMS';

export const SET_FINANCE_DATA = 'SET_FINANCE_DATA';
export const ADD_FINANCE_DATA = 'ADD_FINANCE_DATA';
export const ADD_FINANCES_DATA = 'ADD_FINANCES_DATA';

export const ADD_COIN_DATA = 'ADD_COIN_DATA';

export const SET_FILTER_OPTION = 'SET_FILTER_OPTION';